#Importing Libraries

In [80]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
print("Success")

Success

#Loading Data

In [81]:
df=pd.read_csv('movies_metadata.csv')

#Dataset Inspection

In [82]:
df.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

In [83]:
df.shape

(45466, 24)

In [84]:
df.info

<bound method DataFrame.info of        adult                              belongs_to_collection    budget  \
0      False  {'id': 10194, 'name': 'Toy Story Collection', ...  30000000
1      False                                                NaN  65000000
2      False  {'id': 119050, 'name': 'Grumpy Old Men Collect...         0
3      False                                                NaN  16000000
4      False  {'id': 96871, 'name': 'Father of the Bride Col...         0
...      ...                                                ...       ...
45461  False                                                NaN         0
45462  False                                                NaN         0
45463  False                                                NaN         0
45464  False                                                NaN         0
45465  False                                                NaN         0

                                                  genres  \
0      [{'id': 16, 'name': 'Animation'}, {'id': 35, '...
1      [{'id': 12, 'name': 'Adventure'}, {'id': 14, '...
2      [{'id': 10749, 'name': 'Romance'}, {'id': 35, ...
3      [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...
4                         [{'id': 35, 'name': 'Comedy'}]
...                                                  ...
45461  [{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...
45462                      [{'id': 18, 'name': 'Drama'}]
45463  [{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...
45464                                                 []
45465                                                 []

                                   homepage      id    imdb_id  \
0      http://toystory.disney.com/toy-story     862  tt0114709
1                                       NaN    8844  tt0113497
2                                       NaN   15602  tt0113228
3                                       NaN   31357  tt0114885
4                                       NaN   11862  tt0113041
...                                     ...     ...        ...
45461  http://www.imdb.com/title/tt6209470/  439050  tt6209470
45462                                   NaN  111109  tt2028550
45463                                   NaN   67758  tt0303758
45464                                   NaN  227506  tt0008536
45465                                   NaN  461257  tt6980792

      original_language               original_title  \
0                    en                    Toy Story
1                    en                      Jumanji
2                    en             Grumpier Old Men
3                    en            Waiting to Exhale
4                    en  Father of the Bride Part II
...                 ...                          ...
45461                fa                      رگ خواب
45462                tl          Siglo ng Pagluluwal
45463                en                     Betrayal
45464                en          Satana likuyushchiy
45465                en                     Queerama

                                                overview  ... release_date  \
0      Led by Woody, Andy's toys live happily in his ...  ...   1995-10-30
1      When siblings Judy and Peter discover an encha...  ...   1995-12-15
2      A family wedding reignites the ancient feud be...  ...   1995-12-22
3      Cheated on, mistreated and stepped on, the wom...  ...   1995-12-22
4      Just when George Banks has recovered from his ...  ...   1995-02-10
...                                                  ...  ...          ...
45461        Rising and falling between a man and woman.  ...          NaN
45462  An artist struggles to finish his work while a...  ...   2011-11-17
45463  When one of her hits goes wrong, a professiona...  ...   2003-08-01
45464  In a small town live two brothers, one a minis...  ...   1917-10-21
45465  50 years after decriminalisation of homosexual...  ...   2017-06-09

           revenue runtime                                   spoken_languages  \
0      373554033.0    81.0           [{'iso_639_1': 'en', 'name': 'English'}]
1      262797249.0   104.0  [{'iso_639_1': 'en', 'name': 'English'}, {'iso...
2              0.0   101.0           [{'iso_639_1': 'en', 'name': 'English'}]
3       81452156.0   127.0           [{'iso_639_1': 'en', 'name': 'English'}]
4       76578911.0   106.0           [{'iso_639_1': 'en', 'name': 'English'}]
...            ...     ...                                                ...
45461          0.0    90.0             [{'iso_639_1': 'fa', 'name': 'فارسی'}]
45462          0.0   360.0                  [{'iso_639_1': 'tl', 'name': ''}]
45463          0.0    90.0           [{'iso_639_1': 'en', 'name': 'English'}]
45464          0.0    87.0                                                 []
45465          0.0    75.0           [{'iso_639_1': 'en', 'name': 'English'}]

         status                                            tagline  \
0      Released                                                NaN
1      Released          Roll the dice and unleash the excitement!
2      Released  Still Yelling. Still Fighting. Still Ready for...
3      Released  Friends are the people who let you be yourself...
4      Released  Just When His World Is Back To Normal... He's ...
...         ...                                                ...
45461  Released         Rising and falling between a man and woman
45462  Released                                                NaN
45463  Released                             A deadly game of wits.
45464  Released                                                NaN
45465  Released                                                NaN

                             title  video vote_average vote_count
0                        Toy Story  False          7.7     5415.0
1                          Jumanji  False          6.9     2413.0
2                 Grumpier Old Men  False          6.5       92.0
3                Waiting to Exhale  False          6.1       34.0
4      Father of the Bride Part II  False          5.7      173.0
...                            ...    ...          ...        ...
45461                       Subdue  False          4.0        1.0
45462          Century of Birthing  False          9.0        3.0
45463                     Betrayal  False          3.8        6.0
45464             Satan Triumphant  False          0.0        0.0
45465                     Queerama  False          0.0        0.0

[45466 rows x 24 columns]>

In [85]:
df.columns

Index(['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count'],
      dtype='object')

In [86]:
print(df.columns.tolist())

['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id', 'imdb_id', 'original_language', 'original_title', 'overview', 'popularity', 'poster_path', 'production_companies', 'production_countries', 'release_date', 'revenue', 'runtime', 'spoken_languages', 'status', 'tagline', 'title', 'video', 'vote_average', 'vote_count']

In [87]:
print(df.head(3).to_string())

   adult                                                                                                                                        belongs_to_collection    budget                                                                                             genres                              homepage     id    imdb_id original_language    original_title                                                                                                                                                                                                                                                                                                                                                                                                     overview popularity                       poster_path                                                                                                                 production_companies                                        production_countries release_date      revenue  runtime                                                                   spoken_languages    status                                               tagline             title  video  vote_average  vote_count
0  False        {'id': 10194, 'name': 'Toy Story Collection', 'poster_path': '/7G9915LfUQ2lVfwMEEhDsn3kT4B.jpg', 'backdrop_path': '/9FBwqcd9IRruEDUrTdcaafOMKUq.jpg'}  30000000   [{'id': 16, 'name': 'Animation'}, {'id': 35, 'name': 'Comedy'}, {'id': 10751, 'name': 'Family'}]  http://toystory.disney.com/toy-story    862  tt0114709                en         Toy Story                                                                                              Led by Woody, Andy's toys live happily in his room until Andy's birthday brings Buzz Lightyear onto the scene. Afraid of losing his place in Andy's heart, Woody plots against Buzz. But when circumstances separate Buzz and Woody from their owner, the duo eventually learns to put aside their differences.  21.946943  /rhIRbceoE9lR4veEXuwCC2wARtG.jpg                                                                                       [{'name': 'Pixar Animation Studios', 'id': 3}]  [{'iso_3166_1': 'US', 'name': 'United States of America'}]   1995-10-30  373554033.0     81.0                                           [{'iso_639_1': 'en', 'name': 'English'}]  Released                                                   NaN         Toy Story  False           7.7      5415.0
1  False                                                                                                                                                          NaN  65000000  [{'id': 12, 'name': 'Adventure'}, {'id': 14, 'name': 'Fantasy'}, {'id': 10751, 'name': 'Family'}]                                   NaN   8844  tt0113497                en           Jumanji  When siblings Judy and Peter discover an enchanted board game that opens the door to a magical world, they unwittingly invite Alan -- an adult who's been trapped inside the game for 26 years -- into their living room. Alan's only hope for freedom is to finish the game, which proves risky as all three find themselves running from giant rhinoceroses, evil monkeys and other terrifying creatures.  17.015539  /vzmL6fP7aPKNKPRTFnZmiUfciyV.jpg  [{'name': 'TriStar Pictures', 'id': 559}, {'name': 'Teitler Film', 'id': 2550}, {'name': 'Interscope Communications', 'id': 10201}]  [{'iso_3166_1': 'US', 'name': 'United States of America'}]   1995-12-15  262797249.0    104.0  [{'iso_639_1': 'en', 'name': 'English'}, {'iso_639_1': 'fr', 'name': 'Français'}]  Released             Roll the dice and unleash the excitement!           Jumanji  False           6.9      2413.0
2  False  {'id': 119050, 'name': 'Grumpy Old Men Collection', 'poster_path': '/nLvUdqgPgm3F85NMCii9gVFUcet.jpg', 'backdrop_path': '/hypTnLot2z8wpFS7qwsQHW1uV8u.jpg'}         0                                   [{'id': 10749, 'name': 'Romance'}, {'id': 35, 'name': 'Comedy'}]                                   NaN  15602  tt0113228                en  Grumpier Old Men                                                                      A family wedding reignites the ancient feud between next-door neighbors and fishing buddies John and Max. Meanwhile, a sultry Italian divorcée opens a restaurant at the local bait shop, alarming the locals who worry she'll scare the fish away. But she's less interested in seafood than she is in cooking up a hot time with Max.    11.7129  /6ksm1sjKMFLbO7UY2i6G1ju9SML.jpg                                                      [{'name': 'Warner Bros.', 'id': 6194}, {'name': 'Lancaster Gate', 'id': 19464}]  [{'iso_3166_1': 'US', 'name': 'United States of America'}]   1995-12-22          0.0    101.0                                           [{'iso_639_1': 'en', 'name': 'English'}]  Released  Still Yelling. Still Fighting. Still Ready for Love.  Grumpier Old Men  False           6.5        92.0

In [88]:
print(df.dtypes.to_string())

adult                     object
belongs_to_collection     object
budget                    object
genres                    object
homepage                  object
id                        object
imdb_id                   object
original_language         object
original_title            object
overview                  object
popularity                object
poster_path               object
production_companies      object
production_countries      object
release_date              object
revenue                  float64
runtime                  float64
spoken_languages          object
status                    object
tagline                   object
title                     object
video                     object
vote_average             float64
vote_count               float64

In [89]:
df.isnull().sum()

adult                        0
belongs_to_collection    40972
budget                       0
genres                       0
homepage                 37684
id                           0
imdb_id                     17
original_language           11
original_title               0
overview                   954
popularity                   5
poster_path                386
production_companies         3
production_countries         3
release_date                87
revenue                      6
runtime                    263
spoken_languages             6
status                      87
tagline                  25054
title                        6
video                        6
vote_average                 6
vote_count                   6
dtype: int64

#Removing Duplicates

In [90]:
df.duplicated().sum()

np.int64(13)

In [91]:
df=df.drop_duplicates().reset_index(drop=True)

In [92]:
df.duplicated().sum()

np.int64(0)

In [93]:
df = df[['title', 'overview', 'genres', 'tagline',
         'vote_average', 'popularity']]

#New Shape

In [94]:
df.shape

(45453, 6)

#Removing Null values and filling missing values

In [95]:
df.isnull().sum()

title               6
overview          954
genres              0
tagline         25045
vote_average        6
popularity          5
dtype: int64

In [96]:
df=df.dropna(subset=['title'])

In [97]:
df['overview']=df['overview'].fillna('')

In [98]:
df.iloc[0]['genres']

"[{'id': 16, 'name': 'Animation'}, {'id': 35, 'name': 'Comedy'}, {'id': 10751, 'name': 'Family'}]"

In [99]:
import ast

df['genres'] = df['genres'].apply(
    lambda x: " ".join([i['name'] for i in ast.literal_eval(x)])
)

In [100]:
df.head()

,title,overview,genres,tagline,vote_average,popularity
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...",Animation Comedy Family,NaN,7.7,21.946943
1,Jumanji,When siblings Judy and Peter discover an encha...,Adventure Fantasy Family,Roll the dice and unleash the excitement!,6.9,17.015539
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,Romance Comedy,Still Yelling. Still Fighting. Still Ready for...,6.5,11.7129
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",Comedy Drama Romance,Friends are the people who let you be yourself...,6.1,3.859495
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,Comedy,Just When His World Is Back To Normal... He's ...,5.7,8.387519

In [101]:
df['tagline']=df['tagline'].fillna('')

In [102]:
df.isnull().sum()

title           0
overview        0
genres          0
tagline         0
vote_average    0
popularity      0
dtype: int64

#Making Tags

In [103]:
df['tags']=df['overview']+" "+df['genres']+" "+df['tagline']

In [104]:
df.head()

,title,overview,genres,tagline,vote_average,popularity,tags
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...",Animation Comedy Family,,7.7,21.946943,"Led by Woody, Andy's toys live happily in his ..."
1,Jumanji,When siblings Judy and Peter discover an encha...,Adventure Fantasy Family,Roll the dice and unleash the excitement!,6.9,17.015539,When siblings Judy and Peter discover an encha...
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,Romance Comedy,Still Yelling. Still Fighting. Still Ready for...,6.5,11.7129,A family wedding reignites the ancient feud be...
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",Comedy Drama Romance,Friends are the people who let you be yourself...,6.1,3.859495,"Cheated on, mistreated and stepped on, the wom..."
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,Comedy,Just When His World Is Back To Normal... He's ...,5.7,8.387519,Just when George Banks has recovered from his ...

In [105]:
df['tags'][1]

"When siblings Judy and Peter discover an enchanted board game that opens the door to a magical world, they unwittingly invite Alan -- an adult who's been trapped inside the game for 26 years -- into their living room. Alan's only hope for freedom is to finish the game, which proves risky as all three find themselves running from giant rhinoceroses, evil monkeys and other terrifying creatures. Adventure Fantasy Family Roll the dice and unleash the excitement!"

#NLP section

In [106]:
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import re

In [107]:
from nltk.app import wordnet
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [108]:
stop_words=set(stopwords.words('english'))
lemmatizer=WordNetLemmatizer()

In [109]:
def preprocess_text(text):
    # lowercase
    text = str(text).lower()

    # removing the punctuations
    text = re.sub(r'[^a-zA-Z0-9\s]', '', text)

    # split into words
    words = text.split()

    # remove stopwords
    words = [word for word in words if word not in stop_words]

    # lemmatization
    words = [lemmatizer.lemmatize(word) for word in words]

    # convert list back to string
    return " ".join(words)

In [110]:
df['tags'] = df['tags'].apply(preprocess_text)

In [111]:
df.head()

,title,overview,genres,tagline,vote_average,popularity,tags
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...",Animation Comedy Family,,7.7,21.946943,led woody andys toy live happily room andys bi...
1,Jumanji,When siblings Judy and Peter discover an encha...,Adventure Fantasy Family,Roll the dice and unleash the excitement!,6.9,17.015539,sibling judy peter discover enchanted board ga...
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,Romance Comedy,Still Yelling. Still Fighting. Still Ready for...,6.5,11.7129,family wedding reignites ancient feud nextdoor...
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",Comedy Drama Romance,Friends are the people who let you be yourself...,6.1,3.859495,cheated mistreated stepped woman holding breat...
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,Comedy,Just When His World Is Back To Normal... He's ...,5.7,8.387519,george bank recovered daughter wedding receive...

In [112]:
df['tags'][1]

'sibling judy peter discover enchanted board game open door magical world unwittingly invite alan adult who trapped inside game 26 year living room alans hope freedom finish game prof risky three find running giant rhinoceros evil monkey terrifying creature adventure fantasy family roll dice unleash excitement'

#Converting Into Vectors(Vectorization)
TF-IDF

In [113]:
df=df.reset_index(drop=True)

In [114]:
indices=pd.Series(df.index,index=df['title']).drop_duplicates()
indices

title
Toy Story                          0
Jumanji                            1
Grumpier Old Men                   2
Waiting to Exhale                  3
Father of the Bride Part II        4
                               ...
Subdue                         45442
Century of Birthing            45443
Betrayal                       45444
Satan Triumphant               45445
Queerama                       45446
Length: 45447, dtype: int64

In [115]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [116]:
tfidf=TfidfVectorizer(max_features=50000,ngram_range=(1,2),stop_words='english')

In [122]:
tfidf_matrix=tfidf.fit_transform(df['tags'])

In [123]:
tfidf_matrix

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 1555864 stored elements and shape (45447, 50000)>

#Cosine Similarity

In [124]:
from sklearn.metrics.pairwise import cosine_similarity

In [125]:
def recommend(title,n=10):
  if title not in indices:
    return ['Movie Not Found']
  idx=indices[title]
  sim_score=cosine_similarity(tfidf_matrix[idx],tfidf_matrix).flatten()
  similar_idx=sim_score.argsort()[::-1][1:n+1]
  return df['title'].iloc[similar_idx]

In [131]:
recommend('Toy Story')

2996                Toy Story 2
15344               Toy Story 3
24512                 Small Fry
28972           Superstar Goofy
17184                 Group Sex
6434     What's Up, Tiger Lily?
11396    For Your Consideration
1071      Rebel Without a Cause
1931                  Condorman
485                      Malice
Name: title, dtype: object

In [133]:
import pickle
pickle.dump(tfidf_matrix,open('tfidf_matrix.pkl','wb'))
pickle.dump(indices,open('indices.pkl','wb'))
df.to_pickle('df.pkl')
pickle.dump(tfidf,open('tfidf.pkl','wb'))